import 'dotenv/config';
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomUUID } from 'node:crypto';
import express from 'express';
import cookieParser from 'cookie-parser';
import { PrismaClient } from '@prisma/client';
import { createTaskRouter, taskData } from '../api/taskRoutes.js';
import { encodeSession, decodeSession } from '../api/session.js';

test('sessões rejeitam cookies antigos e adulteração de identidade', () => {
  const signed = encodeSession({ id: 42, role: 'ASSISTENTE' });
  assert.equal(decodeSession(signed).id, 42);
  assert.equal(decodeSession(Buffer.from(JSON.stringify({ id: 1, role: 'ADM' })).toString('base64')), null);
  const [payload, signature] = signed.split('.');
  const altered = JSON.parse(Buffer.from(payload, 'base64url'));
  altered.id = 1;
  assert.equal(decodeSession(`${Buffer.from(JSON.stringify(altered)).toString('base64url')}.${signature}`), null);
  assert.equal(decodeSession(`${signed}.extra`), null);
});

test('validação de tarefas rejeita datas, campos e etapas inválidos', () => {
  assert.throws(() => taskData({ title: ' ' }, true));
  assert.throws(() => taskData({ dueDate: '2026-02-30' }));
  assert.throws(() => taskData({ status: 'inventado' }));
  assert.throws(() => taskData({ important: 'false' }));
  assert.throws(() => taskData({ steps: [{ title: 'documento', done: 'sim' }] }));
  assert.deepEqual(taskData({ title: ' Conferir RG ', steps: [{ title: ' Conferir ', done: false }] }, true), { title: 'Conferir RG', steps: [{ title: 'Conferir', done: false }] });
});

test('API com PostgreSQL: isolamento por perfil, clientes, listas, versões e desfazer', async () => {
  const database = new URL(process.env.DATABASE_URL);
  assert.ok(['localhost', '127.0.0.1'].includes(database.hostname), 'Este teste só pode usar banco local.');
  const prisma = new PrismaClient();
  const userIds = [];
  let clientId;
  let propertyId;
  let server;
  const prefix = `task-test-${randomUUID()}`;
  try {
    const createUser = async (name, role, canManageAllTasks = false) => {
      const user = await prisma.user.create({ data: { nome: name, email: `${prefix}-${name}@example.test`, passwordHash: 'not-a-login-hash', role, canManageAllTasks } });
      userIds.push(user.id); return user;
    };
    const admin = await createUser('Admin','ADM');
    const vanessa = await createUser('Vanessa','ASSISTENTE');
    const other = await createUser('Outro','CORRETOR');
    const manager = await createUser('Gestor','CORRETOR',true);
    clientId = (await prisma.client.create({ data: { nome: prefix } })).id;
    const app = express(); app.use(express.json()); app.use(cookieParser());
    app.use('/tasks',createTaskRouter(prisma,(req,res,next)=>{
      const session=decodeSession(req.cookies.motive_session);
      if(!session)return res.sendStatus(401);
      req.user=session;next();
    }));
    server = app.listen(0,'127.0.0.1');
    await new Promise(resolve=>server.once('listening',resolve));
    const base=`http://127.0.0.1:${server.address().port}/tasks`;
    const request=async (user,path='',method='GET',body) => {
      const response=await fetch(`${base}${path}`,{method,headers:{...(user?{Cookie:`motive_session=${encodeSession({id:user.id,role:'ADM'})}`} : {}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
      const data=await response.json().catch(()=>null);return {status:response.status,data};
    };
    assert.equal((await request(null)).status,401);
    const privateList=(await request(vanessa,'/lists','POST',{name:'Pessoal'})).data;
    const sharedList=(await request(admin,'/lists','POST',{name:'Documentação',shared:true})).data;
    assert.equal((await request(vanessa,'/lists','POST',{name:'Inválida',shared:true})).status,403);
    let own=(await request(admin,'','POST',{title:'Solicitar FGTS',assigneeId:vanessa.id,clientId,listId:privateList.id,steps:[{title:'Conferir documentos',done:false}]})).data;
    assert.ok(own.id);
    assert.equal(own.delegatedById, admin.id);
    const foreign=(await request(admin,'','POST',{title:'Tarefa de outro',assigneeId:other.id,clientId,listId:sharedList.id})).data;
    assert.ok(foreign.id);
    assert.equal((await request(admin, `?view=delegated&clientId=${clientId}`)).data.total, 2);
    assert.equal((await request(vanessa, '?view=delegated')).status, 403);
    assert.equal((await request(manager, '?view=delegated')).status, 403);
    assert.equal((await request(manager, '/options')).data.canManageAll, false);
    assert.deepEqual((await request(manager, '/options')).data.users.map(user => user.id), [manager.id]);
    assert.equal((await request(manager, '', 'POST', { title: 'Permissão antiga não vale', assigneeId: vanessa.id })).status, 403);
    const inbox = (await request(vanessa, '/notifications')).data;
    assert.equal(inbox.unreadCount, 1);
    assert.equal(inbox.items[0].taskId, own.id);
    assert.equal(inbox.items[0].actorName, 'Admin');
    assert.equal(inbox.items[0].task.client.id, clientId);
    assert.equal((await request(admin, '/notifications')).data.unreadCount, 0);
    assert.equal((await request(other, '/notifications')).data.items[0].task.client, null);
    assert.equal((await request(other, `/notifications/${inbox.items[0].id}/read`, 'PATCH')).status, 404);
    assert.equal((await request(admin, `/notifications/${inbox.items[0].id}/read`, 'PATCH')).status, 404);
    assert.equal((await request(vanessa, `/notifications/${inbox.items[0].id}/read`, 'PATCH')).status, 200);
    assert.equal((await request(vanessa, '/notifications')).data.unreadCount, 0);
    const afterReading = (await request(vanessa, `/${own.id}`)).data;
    assert.equal(afterReading.status, 'TODO');
    assert.equal(afterReading.completedAt, null);
    assert.equal(afterReading.version, own.version);
    assert.equal((await request(vanessa)).data.total,1);
    assert.equal((await request(vanessa,`?clientId=${clientId}`)).data.total,1);
    assert.equal((await request(vanessa,`?assigneeId=${other.id}`)).status,403);
    assert.equal((await request(vanessa,`/${foreign.id}`)).status,404);
    assert.equal((await request(vanessa,`/${foreign.id}`,'PATCH',{version:1,status:'DONE'})).status,404);
    assert.equal((await request(vanessa,`/${foreign.id}`,'PATCH',{version:1,remove:true})).status,404);
    assert.equal((await request(vanessa,'','POST',{title:'Atribuir a outro',assigneeId:other.id})).status,403);
    assert.equal((await request(other,'/options')).data.lists.some(list=>list.id===privateList.id),false);
    assert.equal((await request(other,`/${foreign.id}`)).data.client,null);
    assert.equal((await request(other,`/clients?id=${clientId}`)).status,403);
    assert.equal((await request(other,`/${foreign.id}`,'PATCH',{version:1,clientId})).status,403);
    await prisma.task.createMany({ data: Array.from({length:51},(_,i)=>({title:`${prefix}-page-${i}`,assigneeId:other.id,important:true,dueDate:new Date('2000-01-01')})) });
    const firstPage=(await request(other,`?q=${prefix}&view=overdue`)).data;
    const lastPage=(await request(other,`?q=${prefix}&view=overdue&page=2`)).data;
    assert.equal(firstPage.total,51); assert.equal(firstPage.tasks.length,50); assert.equal(lastPage.tasks.length,1);
    assert.equal(new Set([...firstPage.tasks,...lastPage.tasks].map(task=>task.id)).size,51);
    assert.equal((await request(vanessa,`?q=${prefix}`)).data.total,0);
    assert.equal((await request(manager,`/${own.id}`)).status,404);
    await prisma.user.update({where:{id:manager.id},data:{canManageAllTasks:false}});
    assert.equal((await request(manager,`/${own.id}`)).status,404);
    const controlled = await request(vanessa, `/${own.id}`, 'PATCH', { version: own.version, title: 'Solicitar FGTS atualizado', dueDate: '2026-12-10', notes: 'Prazo ajustado por quem recebeu', status: 'WAITING' });
    assert.equal(controlled.status, 200);
    assert.equal(controlled.data.dueDate.slice(0, 10), '2026-12-10');
    assert.equal(controlled.data.title, 'Solicitar FGTS atualizado');
    own = controlled.data;
    const completed=await request(vanessa,`/${own.id}`,'PATCH',{version:own.version,status:'DONE',steps:[{title:'Conferir documentos',done:true}]});
    assert.equal(completed.status,200);
    assert.ok(completed.data.completedAt);
    const historyAfterCompletion = (await request(vanessa, '/notifications')).data;
    assert.equal(historyAfterCompletion.items[0].id, inbox.items[0].id);
    assert.ok(historyAfterCompletion.items[0].readAt);
    assert.equal(historyAfterCompletion.unreadCount, 0);
    const completionNotice = (await request(admin, '/notifications')).data.items.find(item => item.taskId === own.id && item.kind === 'COMPLETED');
    assert.ok(completionNotice);
    assert.equal(completionNotice.actorName, 'Vanessa');
    assert.equal((await request(admin, '?view=delegated&status=done')).data.total, 1);
    assert.equal((await request(admin, '?view=delegated&status=all')).data.total, 2);
    assert.equal((await request(admin, `/notifications/${completionNotice.id}/read`, 'PATCH')).status, 200);
    assert.equal((await request(vanessa)).data.total,0);
    assert.equal((await request(vanessa,'?view=done')).data.total,1);
    assert.equal((await request(vanessa,`/${own.id}`,'PATCH',{version:own.version,title:'Sobrescrever'})).status,409);
    own=(await request(vanessa,`/${own.id}`,'PATCH',{version:completed.data.version,status:'TODO'})).data;
    assert.equal((await request(admin, '/notifications')).data.items.some(item => item.id === completionNotice.id), false);
    const removed=(await request(vanessa,`/${own.id}`,'PATCH',{version:own.version,remove:true})).data;
    assert.equal((await request(vanessa,`/${own.id}`)).status,404);
    assert.equal((await request(vanessa, '/notifications')).data.items.length, 0);
    own=(await request(vanessa,`/${own.id}`,'PATCH',{version:removed.version,restore:true})).data;
    assert.equal(own.deletedAt,null);
    assert.equal((await request(vanessa,`/lists/${privateList.id}`,'DELETE')).status,204);
    assert.equal((await request(vanessa,`/${own.id}`)).data.listId,null);
    // Ordinary edits, completion and restore must not duplicate assignment notices.
    assert.equal((await request(vanessa, '/notifications')).data.items.length, 1);
    own = (await request(admin, `/${own.id}`, 'PATCH', { version: own.version, notes: 'Atualização sem aviso' })).data;
    assert.equal((await request(vanessa, '/notifications')).data.items.length, 1);
    const transferred = await request(admin, `/${own.id}`, 'PATCH', { version: own.version, assigneeId: other.id });
    assert.equal(transferred.status, 200);
    assert.equal((await request(vanessa, '/notifications')).data.items.length, 0);
    assert.equal((await request(vanessa, `/notifications/${inbox.items[0].id}/read`, 'PATCH')).status, 404);
    assert.equal((await request(other, '/notifications')).data.unreadCount, 2);
    assert.equal((await request(admin, `/${own.id}`, 'PATCH', { version: own.version, assigneeId: vanessa.id })).status, 409);
    assert.equal((await request(vanessa, '/notifications')).data.items.length, 0);
    await request(vanessa, '', 'POST', { title: 'Criada por mim' });
    await request(admin, '', 'POST', { title: 'Já concluída', assigneeId: vanessa.id, status: 'DONE' });
    assert.equal((await request(vanessa, '/notifications')).data.items.length, 0);
    // Pagination and bounded read-all preserve notifications arriving after the displayed page.
    await prisma.taskNotification.createMany({ data: Array.from({ length: 35 }, () => ({ taskId: foreign.id, recipientId: other.id, actorName: 'Admin' })) });
    const notices = (await request(other, '/notifications')).data;
    const olderNotices = (await request(other, `/notifications?before=${notices.nextCursor}`)).data;
    assert.equal(notices.items.length, 30);
    assert.equal(olderNotices.items.length, 7);
    assert.equal(new Set([...notices.items, ...olderNotices.items].map(item => item.id)).size, 37);
    await prisma.taskNotification.create({ data: { taskId: foreign.id, recipientId: other.id, actorName: 'Admin' } });
    assert.equal((await request(other, '/notifications/read-all', 'PATCH', { through: notices.items[0].id })).status, 200);
    assert.equal((await request(other, '/notifications')).data.unreadCount, 1);
    const afterReadingAll = (await request(other, `/${foreign.id}`)).data;
    assert.equal(afterReadingAll.status, 'TODO');
    assert.equal(afterReadingAll.completedAt, null);
    assert.equal(afterReadingAll.version, foreign.version);
    // The most recent delegator, not necessarily the creator, owns the follow-up.
    await prisma.user.update({ where: { id: manager.id }, data: { role: 'ADM' } });
    let demand = (await request(admin, '', 'POST', { title: 'Demanda para acompanhar', assigneeId: admin.id, clientId })).data;
    demand = (await request(manager, `/${demand.id}`, 'PATCH', { version: demand.version, assigneeId: vanessa.id })).data;
    assert.equal(demand.createdById, admin.id);
    assert.equal(demand.delegatedById, manager.id);
    assert.equal((await request(manager, '?view=delegated')).data.total, 1);
    assert.equal((await request(manager, '?view=delegated&status=invalid')).status, 400);
    assert.equal((await request(admin, '?view=delegated&status=all')).data.tasks.some(item => item.id === demand.id), false);
    demand = (await request(vanessa, `/${demand.id}`, 'PATCH', { version: demand.version, status: 'DONE' })).data;
    let managerInbox = (await request(manager, '/notifications')).data;
    assert.equal(managerInbox.items.length, 1);
    assert.equal(managerInbox.items[0].kind, 'COMPLETED');
    assert.equal(managerInbox.items[0].task.client.id, clientId);
    assert.equal((await request(other, `/notifications/${managerInbox.items[0].id}/read`, 'PATCH')).status, 404);
    demand = (await request(vanessa, `/${demand.id}`, 'PATCH', { version: demand.version, status: 'DONE', notes: 'Apenas editada' })).data;
    assert.equal((await request(manager, '/notifications')).data.items.length, 1);
    await prisma.user.update({ where: { id: manager.id }, data: { role: 'CORRETOR', canManageAllTasks: true } });
    assert.equal((await request(manager, '/notifications')).data.items.length, 0);
    assert.equal((await request(manager, `/${demand.id}`)).status, 404);
    assert.equal((await request(manager, '?view=delegated')).status, 403);
    await prisma.user.update({ where: { id: manager.id }, data: { role: 'ADM' } });
    demand = (await request(vanessa, `/${demand.id}`, 'PATCH', { version: demand.version, status: 'TODO' })).data;
    assert.equal((await request(manager, '/notifications')).data.items.length, 0);
    demand = (await request(vanessa, `/${demand.id}`, 'PATCH', { version: demand.version, status: 'DONE' })).data;
    managerInbox = (await request(manager, '/notifications')).data;
    assert.equal(managerInbox.items.length, 1);
    assert.equal(managerInbox.unreadCount, 1);
    demand = (await request(vanessa, `/${demand.id}`, 'PATCH', { version: demand.version, status: 'TODO' })).data;
    await prisma.user.update({ where: { id: manager.id }, data: { isActive: false } });
    await request(vanessa, `/${demand.id}`, 'PATCH', { version: demand.version, status: 'DONE' });
    assert.equal(await prisma.taskNotification.count({ where: { taskId: demand.id, kind: 'COMPLETED' } }), 0);
    // Social tasks reuse access rules and link only minimal property data.
    propertyId = (await prisma.property.create({ data: { title: `${prefix} Casa`, code: `${prefix}-CA`, address: `${prefix} Rua das Flores`, city: 'Sumaré', price: 450000, ownerName: 'Não expor no buscador' } })).id;
    assert.equal((await request(other, `/properties?q=${prefix}`)).data[0].id, propertyId);
    assert.equal((await request(other, `/properties?q=${prefix}-CA`)).data[0].id, propertyId);
    assert.equal((await request(other, '/properties?q=Rua%20das%20Flores')).data.some(item => item.id === propertyId), true);
    assert.equal((await request(other, `/properties?id=${propertyId}`)).data[0].ownerName, undefined);
    assert.deepEqual((await request(other, '/properties?q=a')).data, []);
    let postA = (await request(admin, '', 'POST', { title: `${prefix} Publicar imóvel`, category: 'SOCIAL', propertyId, assigneeId: vanessa.id, dueDate: '2026-10-02' })).data;
    let postB = (await request(admin, '', 'POST', { title: `${prefix} Dica institucional`, category: 'SOCIAL', assigneeId: other.id, dueDate: '2026-10-01' })).data;
    const postC = (await request(admin, '', 'POST', { title: `${prefix} Sem data`, category: 'SOCIAL', assigneeId: vanessa.id })).data;
    const queueCheck = (await request(admin, `/properties/${propertyId}/publication-check`)).data;
    assert.equal(queueCheck.tasks.length, 1);
    assert.equal(queueCheck.tasks[0].id, postA.id);
    assert.equal(queueCheck.tasks[0].assignee.nome, 'Vanessa');
    assert.equal(queueCheck.tasks[0].dueDate.slice(0, 10), '2026-10-02');
    assert.equal((await request(other, `/properties/${propertyId}/publication-check`)).data.tasks.length, 0);
    assert.equal((await request(vanessa, `/properties/${propertyId}/publication-check`)).data.tasks.length, 1);
    assert.equal((await request(vanessa, `/properties/${propertyId}/publication-check?exclude=${postA.id}`)).data.tasks.length, 0);
    await prisma.property.update({ where: { id: propertyId }, data: { status: 'Indisponível' } });
    assert.equal((await request(vanessa, `/properties/${propertyId}/publication-check`)).data.property.status, 'Indisponível');
    assert.equal((await request(vanessa, `/${postA.id}`)).data.property.status, 'Indisponível');
    assert.equal(postA.property.id, propertyId);
    assert.equal(postB.property, null);
    assert.equal(postA.socialOrder, postA.id);
    assert.equal((await request(vanessa, '?view=social')).data.total, 2);
    assert.equal((await request(vanessa, `/${postB.id}`)).status, 404);
    assert.equal((await request(admin, '', 'POST', { title: 'Inválida', category: 'SOCIAL', propertyId: 2147483647 })).status, 400);
    assert.equal((await request(admin, `/${postA.id}`, 'PATCH', { version: postA.version, category: 'GENERAL' })).status, 400);
    assert.deepEqual((await request(admin, `?view=social&q=${prefix}`)).data.tasks.map(item => item.id), [postB.id, postA.id, postC.id]);
    assert.deepEqual((await request(admin, `?view=social&order=manual&q=${prefix}`)).data.tasks.map(item => item.id), [postA.id, postB.id, postC.id]);
    assert.equal((await request(vanessa, `/${postA.id}/social-order`, 'PATCH', { version: postA.version, direction: 'down' })).status, 403);
    assert.equal((await request(admin, `/${postB.id}/social-order`, 'PATCH', { version: postB.version, direction: 'up' })).status, 200);
    assert.deepEqual((await request(admin, `?view=social&order=manual&q=${prefix}`)).data.tasks.map(item => item.id), [postB.id, postA.id, postC.id]);
    assert.equal((await request(admin, `/${postB.id}/social-order`, 'PATCH', { version: postB.version, direction: 'down' })).status, 409);
    postA = (await request(vanessa, `/${postA.id}`)).data;
    postA = (await request(vanessa, `/${postA.id}`, 'PATCH', { version: postA.version, status: 'DONE' })).data;
    assert.equal((await request(admin, `/properties/${propertyId}/publication-check`)).data.tasks.length, 0);
    assert.equal((await request(vanessa, '?view=social')).data.total, 1);
    assert.equal((await request(vanessa, '?view=social&status=done')).data.tasks[0].id, postA.id);
    assert.equal((await request(admin, `/${postA.id}/social-order`, 'PATCH', { version: postA.version, direction: 'down' })).status, 404);
    // Removing an optional property must preserve the publication task.
    await prisma.property.delete({ where: { id: propertyId } }); propertyId = null;
    assert.equal((await request(vanessa, `/${postA.id}`)).data.propertyId, null);
    await prisma.user.update({where:{id:vanessa.id},data:{isActive:false}});
    assert.equal((await request(vanessa)).status,401);
    assert.equal((await request(vanessa, '/notifications')).status, 401);
  } finally {
    if(server)await new Promise(resolve=>server.close(resolve));
    if(userIds.length) {
      await prisma.task.deleteMany({where:{assigneeId:{in:userIds}}});
      await prisma.taskList.deleteMany({where:{ownerId:{in:userIds}}});
      await prisma.user.deleteMany({where:{id:{in:userIds}}});
    }
    if(clientId)await prisma.client.delete({where:{id:clientId}});
    if(propertyId)await prisma.property.delete({where:{id:propertyId}});
    await prisma.$disconnect();
  }
});
